CREATE TABLE [{@Schema}].[CapturedPlan](
  [CapturedPlan_id] [int] IDENTITY(1,1) NOT NULL,
  [name] [nvarchar](max) NULL,
  [timestamp] [datetimeoffset](7) NULL,
  [timestamp (UTC)] [datetimeoffset](7) NULL,
  [source_database_id] [bigint] NULL, 
  [object_type] [nvarchar](max) NULL,
  [object_id] [int] NULL,
  [nest_level] [int] NULL,
  [cpu_time] [bigint] NULL,
  [duration] [bigint] NULL,
  [estimated_rows] [int] NULL,
  [estimated_cost] [int] NULL,
  [serial_ideal_memory_kb] [decimal](20, 0) NULL,
  [requested_memory_kb] [decimal](20, 0) NULL,
  [used_memory_kb] [decimal](20, 0) NULL,
  [ideal_memory_kb] [decimal](20, 0) NULL,
  [granted_memory_kb] [decimal](20, 0) NULL,
  [dop] [bigint] NULL,
  [object_name] [nvarchar](max) NULL,
  [showplan_xml] [nvarchar](max) NULL,
  [showplan_xml_compressed] [varbinary](max) NULL,
  [database_name] [nvarchar](max) NULL,
  [transaction_id] [bigint] NULL,
  [sql_text] [nvarchar](max) NULL,
  [sql_text_compressed] [varbinary](max) NULL,
  [query_plan_hash] [varbinary](max) NULL,
  [query_hash] [varbinary](max) NULL,
  [nt_username] [nvarchar](max) NULL,
  [client_hostname] [nvarchar](max) NULL,
  [task_time] [decimal](20, 0) NULL,
  [begin_offset] [numeric](20, 0) NULL,	
  [end_offset] [numeric](20, 0) NULL,
  [plan_handle] [varbinary](max) NULL,	
  [sql_handle] [varbinary](max) NULL,
  [recompile_count] [decimal](20, 0) NULL,
  [sourcetype] [nvarchar](128),
  [source] [nvarchar] (max) NULL,
  [query_id] [bigint] NULL,
  [plan_id] [bigint] NULL,
  [notes] [nvarchar] (max) NULL,
  [processed] [bit] NOT NULL
)