CREATE TABLE [{@Schema}].[Relop]
(
  [Relop_id] [int] IDENTITY(1,1) NOT NULL,
  [CapturedPlan_id] [int] NOT NULL,                     
  [AvgRowSize][float] NOT NULL,                                         
  [EstimateCPU][float] NOT NULL, 
  [EstimateIO] [float] NOT NULL,                                    
  [EstimateRebinds] [float] NOT NULL,                                  
  [EstimateRewinds] [float] NOT NULL,                                 
  [EstimatedExecutionMode] varchar(5) NULL,    
  [GroupExecuted] [bit] NULL,  
  [EstimateRows] [float] NOT NULL,   
  [EstimateRowsWithoutRowGoal] [float] NULL, 
  [EstimatedRowsRead] [float] NULL,  
  [LogicalOp] varchar(32) NOT NULL,                                         
  [NodeId] [int] NULL,
  [Parallel] [bit] NOT NULL,    
  [RemoteDataAccess] [bit] NULL, 
  [Partitioned] [bit] NULL,                                   
  [PhysicalOp] varchar(32) NOT NULL,  
  [IsAdaptive] [bit] NULL,
  [AdaptiveThresholdRows] [float] NULL, 
  [EstimatedTotalSubtreeCost] [float] NOT NULL, 
  [TableCardinality][float] NULL,
  [StatsCollectionId] [int] NULL,
  [EstimatedJoinType] varchar(32) NULL,                             
  [HyperScaleOptimizedQueryProcessing] varchar(32) NULL,            
  [HyperScaleOptimizedQueryProcessingUnusedReason] varchar(32) NULL,  
  [EstimateNumberOfExecutions] [float] NULL, 
  [EstimateNumberOfRowsForAllExecutions] [float] NULL
) 