CREATE TABLE [{@Schema}].[RunTimeCountersPerThread]
(
  [CapturedPlan_id] [int] NOT NULL,
  [Relop_id] [int] NOT NULL,
  [Thread_id] [int] NOT NULL,
  [ActualCPUms] [decimal](38,0) NULL,
  [ActualElapsedms] [decimal](38,0) NULL,
  [ActualEndOfScans] [int] NULL,
  [ActualExecutionMode] [varchar](5) NULL,
  [ActualExecutions] [decimal](38,0) NULL,
  [ActualJoinType] [varchar](32) NULL,   
  [ActualLobLogicalReads] [int] NULL,
  [ActualLobPageServerReadAheads] [int] NULL,
  [ActualLobPageServerReads] [int] NULL,
  [ActualLobPhysicalReads] [int] NULL,
  [ActualLobReadAheads] [int] NULL,
  [ActualLocallyAggregatedRows] [int] NULL,
  [ActualLogicalReads] [decimal](38,0) NULL,
  [ActualPageServerPushedPageIDs] [int] NULL,
  [ActualPageServerPushedReads] [int] NULL,    
  [ActualPageServerReadAheads] [int] NULL,
  [ActualPageServerReads] [int] NULL,
  [ActualPageServerRowsRead] [int] NULL,
  [ActualPageServerRowsReturned] [int] NULL,
  [ActualPhysicalReads] [decimal](38,0) NULL,
  [ActualReadAheads] [int] NULL,
  [ActualRebinds] [int] NULL,
  [ActualRewinds] [int] NULL,
  [ActualRows] [decimal](38,0) NULL,
  [ActualRowsRead] [decimal](38,0) NULL,
  [ActualScans] [decimal](38,0) NULL,
  [Batches] [int] NULL,
  [BrickId] [int] NULL,
  [CloseTime] [int] NULL,
  [FirstActiveTime] [int] NULL,
  [FirstRowTime] [int] NULL,
  [HpcDeviceToHostBytes] [int] NULL,
  [HpcHostToDeviceBytes] [int] NULL,
  [HpcKernelElapsedUs] [int] NULL,
  [HpcRowCount] [int] NULL,
  [InputMemoryGrant] [int] NULL,
  [IsInterleavedExecuted] [bit] NULL,
  [LastActiveTime] [int] NULL,
  [LastRowTime] [int] NULL,
  [NodeId] [int] NOT NULL,
  [OpenTime] [int] NULL,
  [OutputMemoryGrant] [int] NULL,
  [RowRequalifications] [int] NULL,
  [SchedulerId] [int] NULL,
  [SegmentReads] [int] NULL,
  [SegmentSkips] [int] NULL,
  [TaskAddr] [int] NULL,
  [Thread] [int] NULL,
  [UsedMemoryGrant] [int] NULL
) 