CREATE TABLE [{@Schema}].[StmtSimple_staging]
(
  [CapturedPlan_id] [int] NOT NULL,
  [StatementCompId] [int] NULL,
  [StatementEstRows] [float] NULL, 
  [StatementId] [int] NULL,
  [QueryCompilationReplay] [int] NULL,
  [StatementOptmLevel] [varchar](32) NULL,
  [StatementOptmEarlyAbortReason] [varchar] (20) NULL,
  [CardinalityEstimationModelVersion] [int] NULL,
  [StatementSubTreeCost] [float] NULL, 
  [StatementText] [nvarchar] (max) NULL,
  [StatementType] [nvarchar] (128) NULL,
  [TemplatePlanGuideDB] [nvarchar] (256) NULL,
  [TemplatePlanGuideName] [nvarchar] (256) NULL,
  [PlanGuideDB] [nvarchar] (128) NULL,
  [PlanGuideName] [nvarchar] (256) NULL,
  [ParameterizedText] [nvarchar] (max) NULL,
  [ParameterizedPlanHandle] [nvarchar] (max) NULL,
  [QueryHash] [nvarchar] (max) NULL,
  [QueryPlanHash] [nvarchar] (max) NULL,
  [RetrievedFromCache] [bit] NULL,
  [StatementSqlHandle] [nvarchar] (max) NULL,
  [DatabaseContextSettingsId] [int] NULL,
  [ParentObjectId] [int] NULL,
  [BatchSqlHandle] [nvarchar] (max) NULL,
  [StatementParameterizationType] [int] NULL,
  [SecurityPolicyApplied] [bit] NULL,
  [BatchModeOnRowStoreUsed] [bit] NULL,
  [QueryStoreStatementHintId] [int] NULL,
  [QueryStoreStatementHintText] [nvarchar] (256) NULL,
  [QueryStoreStatementHintSource] [nvarchar] (256) NULL,
  [ContainsLedgerTables]  [bit] NULL
) 