CREATE TABLE [{@Schema}].[Warning](
  [Warning_id] [int] IDENTITY(1,1) NOT NULL,
  [CapturedPlan_id] [int] NOT NULL,
  [IsColumnsWithNoStatistics] [bit] DEFAULT 0,
  [IsColumnsWithStaleStatistics] [bit] DEFAULT 0,
  [IsExchangeSpillDetails] [bit] DEFAULT 0,
  [IsHashSpillDetails] [bit] DEFAULT 0,
  [IsMemoryGrantWarning] [bit] DEFAULT 0,
  [IsNoJoinPredicate] [bit] DEFAULT 0,
  [IsPlanAffectingConvert] [bit] DEFAULT 0,
  [IsSortSpillDetails] [bit] DEFAULT 0,
  [IsSpillOccurred] [bit] DEFAULT 0,
  [IsSpillToTempDb] [bit] DEFAULT 0,
  [IsUnmatchedIndexes] [bit] DEFAULT 0,
  [IsWait] [bit] DEFAULT 0,
  [Server] [nvarchar](128) NULL,
  [Database] [nvarchar](128) NULL,
  [Schema] [nvarchar](128) NULL,
  [Table] [nvarchar](128) NULL,
  [Alias] [nvarchar](128) NULL,
  [Index] [nvarchar](128) NULL,
  [Column] [nvarchar](128) NULL,
  [ComputedColumn] [bit] NULL,
  [ParameterDataType] [nvarchar](128) NULL,
  [ParameterCompiledValue] [nvarchar](max) NULL,
  [ParameterRuntimeValue] [nvarchar](max) NULL,
  [ConvertIssue] [varchar](20)  NULL,
  [Expression] [varchar](MAX)  NULL,
  [GrantWarningType] [varchar](23) NULL,
  [RequestedMemory] [decimal](38,0) NULL,
  [GrantedMemory] [decimal](38,0) NULL,
  [MaxUsedMemory] [decimal](38,0) NULL,
  [SpillLevel] [int] NULL,
  [SpilledThreadCount] [int] NULL,
  [GrantedMemoryKb] [int] NULL,
  [UsedMemoryKb] [int] NULL,
  [WritesToTempDb] [int] NULL,
  [ReadsFromTempDb] [int] NULL,
  [WaitType] [varchar](128) NULL,
  [WaitTime] [int] NULL,
  [Detail] [bit] NULL
)