CREATE VIEW [{@Schema}].[vw_CapturedPlan]
AS
SELECT
  [CapturedPlan_id],
  [name],
  [timestamp],
  [timestamp (UTC)],
  [source_database_id], 
  [object_type],
  [object_id],
  [nest_level],
  [cpu_time],
  [duration],
  [estimated_rows],
  [estimated_cost],
  [serial_ideal_memory_kb],
  [requested_memory_kb],
  [used_memory_kb],
  [ideal_memory_kb],
  [granted_memory_kb],
  [dop],
  [object_name],
  COALESCE([showplan_xml], CAST(DECOMPRESS([showplan_xml_compressed]) AS [nvarchar](max))) AS [showplan_xml],
  [database_name],
  [transaction_id],
  COALESCE([sql_text], CAST(DECOMPRESS([sql_text_compressed]) AS [nvarchar](max))) AS [sql_text],
  [query_plan_hash],
  [query_hash],
  [nt_username],
  [client_hostname],
  [task_time],
  [begin_offset],	
  [end_offset],
  [plan_handle],	
  [sql_handle],
  [recompile_count],
  [sourcetype],
  [source],
  [query_id],
  [plan_id],
  [notes],
  [processed]
FROM [{@Schema}].[CapturedPlan]